name: Release
on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: stack install --local-bin-path ./bin
    - name: Deploy to Heroku
      uses: jctaveras/heroku-deploy@v2.1.17
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_path: '.'
